### ISSUE TITLE
When should the nudger give up?

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1103] opened 2015-05-12 23:23 UTC
This item has been retrying since December https://www.popuparchive.com/api/collections/2448/items/29282. If we get a lot of these it could gum up the works.

**Comment by pkarman** [comment] 2015-05-13 01:30
wow. 1700+ tasks.

the nudger keeps trying until an AudioFile is considered "final" which is when it has a transcript. If it won't ever have a transcript (because the file is missing or un-transcribe-able) we should probably have a new state for that AudioFile to be set to to prevent this kind of thing. I'll have to give this some thought.

**Comment by pkarman** [comment] 2015-05-13 01:31
I think this recursive loop was caused by the cached audio_file status feature that went into production last month. I'll work on closing that loop first.

**Comment by baileyspace** [comment] 2015-05-13 02:14
I'd be happy to say the audio file gets X chances to complete. If it fails to complete in X iterations we could send an email to edison or add it the dashboard so that we don't lose track of items/are aware of trends that cause failures. 

Also of note is that this transcribe task (392332) is marked complete in fixer http://beta.fixer.prx.org/tasks/533486. Is this another non-ascii error?

**Comment by pkarman** [comment] 2015-05-13 15:21
Here's what I've come up with.

After MAX_TTL seconds, if an audio_file is not complete with a transcript, then it goes to Cancelled status, and no more tasks will be automatically created for it. If any subsequent tasks finish (for whatever reason) then the status should change to reflect those finished tasks. Likewise, the file could be manually re-activated by clicking the Recover button in superadmin, or calling the check_tasks() method (which is the same thing the Recover button does).

I've got MAX_TTL set to 3 days, merged to master and deployed. Let's see if this helps.

**Comment by pkarman** [comment] 2015-05-13 15:31
https://www.popuparchive.com/superadmin/audio_files/34763 now has a status of Cancelled, which in theory should prevent it from spawning any new tasks automatically.

**Comment by pkarman** [comment] 2015-05-13 21:05
audio_files canceling themselves in earnest since this morning:

```
pop-up-archive::RED=> select id,updated_at from audio_files where status_code = 'X';
  id   |         updated_at         
-------+----------------------------
  4999 | 2015-05-13 15:24:45.451217
  9446 | 2015-05-13 15:26:48.646076
  9443 | 2015-05-13 17:03:42.718352
 11316 | 2015-05-13 17:07:40.180483
 11375 | 2015-05-13 17:10:07.201427
 11403 | 2015-05-13 17:04:00.64431
 11401 | 2015-05-13 17:06:51.523064
 11399 | 2015-05-13 17:08:57.436994
 11435 | 2015-05-13 17:09:51.407177
 11437 | 2015-05-13 17:13:07.071154
 11456 | 2015-05-13 17:09:20.804527
 11458 | 2015-05-13 17:10:27.549856
 11495 | 2015-05-13 17:11:17.109083
 11482 | 2015-05-13 17:12:03.674931
 11480 | 2015-05-13 17:08:42.230023
 11249 | 2015-05-13 17:11:32.583263
 11497 | 2015-05-13 17:10:45.79302
 11484 | 2015-05-13 17:09:35.968971
 11478 | 2015-05-13 17:11:02.054594
 11454 | 2015-05-13 17:11:48.488771
 11379 | 2015-05-13 17:07:55.583794
 13532 | 2015-05-13 15:36:16.505987
 13887 | 2015-05-13 17:12:18.860128
 17103 | 2015-05-13 15:54:55.258963
 17133 | 2015-05-13 15:29:07.865046
 17198 | 2015-05-13 15:26:39.569264
 43844 | 2015-05-13 15:24:56.074745
 17184 | 2015-05-13 15:27:52.621998
 17205 | 2015-05-13 15:25:06.541345
 17255 | 2015-05-13 15:28:09.683199
 13521 | 2015-05-13 17:03:22.949497
 17101 | 2015-05-13 15:26:50.108838
 17390 | 2015-05-13 17:14:21.134327
 17397 | 2015-05-13 17:04:53.465593
 17389 | 2015-05-13 17:12:51.915648
 17398 | 2015-05-13 17:03:07.735602
 34847 | 2015-05-13 15:24:12.111862
 17102 | 2015-05-13 15:26:36.777385
 34815 | 2015-05-13 15:38:04.542726
 34737 | 2015-05-13 15:27:55.045305
 34701 | 2015-05-13 15:28:04.476333
 42745 | 2015-05-13 15:25:00.19299
 34697 | 2015-05-13 15:26:04.444292
 33470 | 2015-05-13 16:41:17.766098
 33495 | 2015-05-13 15:33:36.852581
 34813 | 2015-05-13 15:29:36.734866
 24800 | 2015-05-13 18:03:44.459139
 43696 | 2015-05-13 15:27:46.91596
 17264 | 2015-05-13 15:28:34.173241
 27098 | 2015-05-13 18:03:29.14046
 11329 | 2015-05-13 17:07:24.768213
 17089 | 2015-05-13 15:33:59.218614
 32486 | 2015-05-13 15:26:35.935436
 33571 | 2015-05-13 15:24:59.375422
 11290 | 2015-05-13 17:03:38.381155
 11413 | 2015-05-13 17:07:06.692006
 11385 | 2015-05-13 17:08:11.218394
 11383 | 2015-05-13 17:08:26.790555
 12419 | 2015-05-13 17:06:35.908449
 11199 | 2015-05-13 17:04:16.544609
 33517 | 2015-05-13 17:09:02.486298
 34763 | 2015-05-13 15:34:13.402538
 34584 | 2015-05-13 15:28:39.978344
 11345 | 2015-05-13 17:06:21.017788
(64 rows)
```

**Comment by pkarman** [comment] 2015-05-18 14:44
This continues to run in production. Closing.

**Closed by pkarman** 2015-05-18 14:44 UTC
Labels: bug, ready-to-deploy, ready-to-test
