### ISSUE TITLE
Update pricing page w/ free trial info

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#1168] opened 2015-07-14 00:32 UTC

**Comment by tarakieffer** [comment] 2015-08-05 12:52
![screen shot 2015-08-05 at 7 51 44 am](https://cloud.githubusercontent.com/assets/9256525/9085968/e8bd3e3a-3b46-11e5-99b1-d2b6787f6f1a.png)

**Comment by Saltzshaker** [comment] 2015-08-07 21:56
@baileyspace @annewootton How do you all feel about changing the title to something like "1 Hour Demo?" Right now it is not very clear that it is one hour total, for all-time. 

Also, should we take out the Premium/Basic comparison, since basic will no longer be offered on the site?

**Comment by Saltzshaker** [comment] 2015-08-07 21:58
Also, will on-demand ordering be officially be gone as part of this milestone? If so, we (or I) should update the Pricing page/Zendesk FAQ accordingly.

**Comment by annewootton** [comment] 2015-08-07 21:59
I think there is a separate ticket for taking out the Premium/Basic
comparison — if you want to pull it into this milestone, fine by me.

Defer to @baileyspace & @saltzshaker on changing the title of the plan on
the pricing page.
ᐧ

**Comment by annewootton** [comment] 2015-08-07 21:59
And yes to taking out on-demand ordering from the pricing page + FAQ!
ᐧ

**Comment by annewootton** [comment] 2015-08-07 22:00
https://github.com/popuparchive/pop-up-archive/issues/837
ᐧ

**Comment by Saltzshaker** [comment] 2015-08-07 22:04
Assigned to me. Will change plan name to "1 Hour Demo" and update faq.

**Comment by Saltzshaker** [comment] 2015-08-12 17:55
To test: there is no mention of basic transcripts, or ordering transcripts on demand. It is clear that the free "plan" is limited to uploading one hour, total (not monthly).

**Comment by Saltzshaker** [comment] 2015-08-12 17:57
@baileyspace or @karpet, can you deploy https://github.com/popuparchive/pop-up-archive/commit/339281d0b3288a9967b29bd6996c3391d49fe907 to Linda in staging?

**Comment by Saltzshaker** [comment] 2015-08-12 18:44
Also to test: Changed Community plan name in "Stripe Test" to 1 Hour Demo. Test that sign up works as intended for free plan with new name.

**Comment by pkarman** [comment] 2015-08-12 18:47
change deployed to stage

**Comment by pkarman** [comment] 2015-08-12 18:51
FWIW: the plan name is important and is hard-coded into the code base. If you change it to something else, then the stripe id must still be **premium_community** or the code must be changed.

**Comment by baileyspace** [comment] 2015-08-12 18:58
It should be fine. Just the name was changed, not the id.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-08-12 11:51 GMT-07:00 Peter Karman <notifications@github.com>:

**Comment by tarakieffer** [comment] 2015-08-20 13:04
Name of plan is '1 Hour Demo' in the UI, superadmin and in Stripe
![screen shot 2015-08-20 at 7 53 32 am](https://cloud.githubusercontent.com/assets/9256525/9383861/bee14ae4-4711-11e5-80c0-37e6cab0f3b9.png)

Only mention I am seeing to Basic transcripts is on the items with Basic transcripts.

**Closed** 2015-08-25 00:21 UTC
Labels: live-in-staging, ready-to-deploy, ready-to-test
