### ISSUE TITLE
Why did these feeds get basic transcripts?

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1304] opened 2015-11-16 19:55 UTC
Why do some collections hooked up to feeds alternate between basic and premium transcripts? Examples: 
* WILL News example from 10/2/15: one is basic and one is premium https://www.popuparchive.com/superadmin/collections/1468
  * 44456	Vintage Vinyl Sale Saturday	Premium transcript complete	2015-10-03 01:30:44 UTC	243	TRUE
  * 44410	Quinn: Budget Impasse “Disappointing” But Won’t Run For Office	Basic transcript complete	2015-10-02 01:31:00 UTC
  * 44409	Máiréad Nesbitt Of Celtic Woman: Last Ten Years Have Been A ‘Wonderful Journey’	Basic transcript complete	2015-10-02 01:30:59 UTC
* WWLA example from 7/28/15 and 7/29/15: https://www.popuparchive.com/superadmin/collections/2347 
  * 41677	Murky Link between SoLA Violence and Social Media Chatter	Basic transcript complete	2015-07-29 09:00:49 UTC
  * 41610	The Much Needed Repairs of LA Roads and California Freeways	Premium transcript complete	2015-07-28 09:00:51 UTC

Note, no changes were made to the org owners' plans during these times.

**Comment by Saltzshaker** [comment] 2015-11-18 20:47
For reference, I made a spreadsheet and sorted the feed items by creation date: https://docs.google.com/spreadsheets/d/1D5X99hagYF3diOEzlpTBRtgtXk7nzWwjDwvqgkGTMAE/edit?usp=sharing

**Comment by AndersEverett** [comment] 2015-11-26 00:23
Columns added to spreadsheet with file's user, user.entity, and collection.billable_to. These are varied and are generally NOT the expected org who owns the feed. Since transcript type looks to user plan, could this be the reason?

**Comment by AndersEverett** [comment] 2015-12-01 21:33
Per stand-up discussion: these items all currently have the correct owner(creator) assignments, but historically have had popuparchive as assigned creator. Issue defined on ticket has not been reproducible for 2 months, so closing under assumption that varying user/ownership impacted transcript type.

**Closed** 2015-12-01 21:33 UTC
Labels: high
