### ISSUE TITLE
Search paging only works for batches of 10 items

### ISSUE THREAD

**Issue by baileyspace** [popuparchive/pop-up-archive#486] opened 2014-04-12 21:18 UTC
I.E. The last item in a page of search results will not link to the next item in the next batch of search results on the item page

![image](https://cloud.githubusercontent.com/assets/833332/2688170/ea953c00-c287-11e3-9d45-acd71802815d.png)

**Comment by pkarman** [comment] 2015-01-15 04:35
As requested, I spent a couple hours researching this issue.

I can see quite clearly where in the code the problem is manifest (app/assets/javascripts/angular/services/search.js.erb in getItem()) but a solution seems either (a) too involved to solve quickly, and/or (b) requiring a re-think of how the search paging architecture works. 

There are multiple problems. The first is, although the code attempts to fetch the next page of results, the query string is serialized JSON instead of a plain string. I'm not sure if that is intended, but the server does not seem to handle that case (decoding the JSON string into an object on the server). So it's a bug on the client or the server side (my money is on the client).

Once the code is changed to request a simple string instead of JSON-encoded string, the 2nd problem is that the resulting "promise" object does not create a url string when getItem().link() is called. It is, in fact, quite easy to break the Previous and Next links within a set of results, depending on the order in which you click things. I.e. the problem is not limited to the last item in a page of results.

As I think I've said before, the navigation of search results is tricky to get right when you venture beyond the de facto google standard of pagination links. In this case, I would be more interested in re-examining what UX problem was being addressed with this Previous/Next solution, and if perhaps there is a different approach we could take that would sidestep this particular problem entirely.

**Comment by baileyspace** [comment] 2015-01-15 04:44
That sounds reasonable to me. How do we feel about pull the previous and
next buttons entirely until we come up with a better solution?

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-01-14 20:35 GMT-08:00 Peter Karman <notifications@github.com>:

**Comment by pkarman** [comment] 2015-01-15 04:46
That seems sane.

**Comment by baileyspace** [comment] 2015-01-15 04:53
One of my finer qualities.

---
Bailey R. Smith, MIMS
Pop Up Archive
http://popuparchive.com

              ,
             / \,,_  .'|
          ,{{| /}}}}/_.'
         }}}}` '{{'  '.
       {{{{{    _   ;, \
    ,}}}}}}    /o`\  ` ;)
   {{{{{{   /           (
   }}}}}}   |            \
  {{{{{{{{   \            \
  }}}}}}}}}   '.__      _  |
  {{{{{{{{       /`._  (_\ /
   }}}}}}'      |    //___/
   `{{{{`       |     '--'
    }}}`


2015-01-14 20:46 GMT-08:00 Peter Karman <notifications@github.com>:

**Comment by pkarman** [comment] 2015-01-15 04:54
committed and pushed to master.

**Closed** 2015-03-24 18:13 UTC
Labels: bug, high, one-day, wontfix
