### ISSUE TITLE
Plan discrepancy between Stripe plans (month from sign up) and PUA plan reporting (calendar month)

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1011] opened 2015-02-20 19:56 UTC
Pop Up Archive limits and overage reporting go by the calendar month, but limits should be based on the month from signup date (Stripe is charging by month from date of sign up.)

@annewootton realized this for the CBC. @pkarman @baileyspace thoughts?

**Comment by annewootton** [comment] 2015-02-20 20:03
If you look at the CBC org (https://www.popuparchive.com/superadmin/organizations/32), you'll see 35 hours uploaded for Feb. They were on a Mechaplan (holdover from their pilot phase) and today I switched them to the 25 hr/month plan. Their Stripe billing cycle starts on the 17th of each month, so technically the limit should start counting from 2/17, right? But in fact, their users are being told they're over their limit. See what I mean?

(For the CBC it's not an urgent problem because they *actually* signed a contract that starts on the 1st of the month and were billed separately, so they are in fact over their limits. But for anyone who signs up self-serve on a date other than the 1st of the month, there seems to be a discrepancy between Stripe/superadmin.)

**Comment by annewootton** [comment] 2015-02-20 20:04
If you want to check Stripe, I won't put the customer ID here, but it's PUA user 1023.

**Comment by pkarman** [comment] 2015-02-20 20:04
well.

well well well.

that was an assumption I didn't have when doing all the billing work.

It would be very difficult to re-write all the billing code to assume a "month" is a relatively arbitrary period of time (30 days? 31?, 28?), beginning on an arbitrary day.

Is there no way to force-align Stripe to bill from first-day-of-calendar month and then pro-rate the rest?

**Comment by annewootton** [comment] 2015-02-20 20:05
I'll look into Stripe.

**Comment by annewootton** [comment] 2015-02-21 00:56
Lo and behold: https://support.stripe.com/questions/how-can-i-change-the-billing-cycle-of-a-subscription. It can be done through the API, at least sort of.

The only questions this leaves me with are:
1) When a new user subscribes, will they effectively get a free trial until the 1st of whatever month comes next? How can we charge them for that partial month?
2) What about existing users? If we send them an email that we're switching to billing on the 1st of each month, I could manually re-subscribe them all (or we could update their subscriptions through API I suppose) so they're all trialing until 2/28, with new billing cycle set to start 3/1. But maybe we'd want to leave "Prorate" checked so they get credited for whatever unused time they had from their old billing cycle when things reset on 3/1. I'm not sure that quite works...

**Comment by pkarman** [comment] 2015-02-22 21:28
re (1) I guess it depends on whether we imagine customers are paying in advance for the month to come, or paying in arrears for the month just past. If it's the former, then we could do a one-time prorated manual charge, I suppose. If it's the latter, then we'd have to think about prorated manual refunds should a customer cancel mid-month (though maybe Stripe does that for us).

re (2) if we do a global change, we can automate it, AFAIK. Yes, we should notify customers so it is clear what the usage constraints are, though "unused" time is tricky since we've been counting overages per-calendar-month since December. I don't have a strong opinion here; we're still small enough, and our subscribing users mostly not going over their allotments, that I'm sure we can negotiate if any customer is unhappy.

**Comment by annewootton** [comment] 2015-02-24 00:22
Let me make sure I understand before forming a final opinion on this. Let's
assume we are talking about a user signing up on February 24th for the
$20/month plan.

If customers pay in advance for the month to come: we'd charge a prorated
(< $20) amount for Feb. 24-28. The customer would be entitled to a full
hour of transcripts even though they only paid for four days in February.
Then their limit would resent and they'd get billed $20 on March 1st.

If customers pay in arrears for the month just past: we'd charge $20 on
Feb. 24. The customer would be entitled to a full hour of transcripts from
Feb 24-28. Then their limit would reset and they'd get billed $20 again on
March 1st.

Is this right? Neither seems perfect, but if forced to choose the former
seems like the way to go, since I think customers would find the latter (as
I understand it at least) misleading.

**Comment by pkarman** [comment] 2015-02-24 15:15
yes those examples seem to accurately reflect reality.

I agree: no perfect solution. Also agreed: least even is the pay-in-advance perspective. At worst, we are giving away a free slightly-less-than-a-month, if we choose not to do a manual charge.

**Comment by annewootton** [comment] 2015-02-24 23:26
Sorry, I don't understand this: 
" Also agreed: least even is the pay-in-advance perspective." Do you mean most even?

I think the pay-in-advance perspective makes the most sense, b/c it doesn't seem fair to charge people $20 for four days of service. To me, the only imperfect aspect of the pay-in-advance perspective is that even with a manual prorated charge (i.e. for Feb 24-28), in terms of metering (i.e. the one hour limit) we're giving people the same amount of product for less money (i.e. the user who gets charged a prorated charge for Feb 24-28 can still upload a full hour of audio). But we're giving them less time to use the product (i.e. four days). I am fine with that if you are! And manually charging a pro-rated amount avoids the worst-case scenario, unless it's a ton of extra work for you to code, in which case, let's talk.

So @pkarman — if we are on the same page, we need to change the code so it charges a prorated amount on the day of signup for the remainder of the month, then free trials the user until the 1st of the next month. Sound right to you?

**Comment by pkarman** [comment] 2015-02-25 01:27
Sorry, I meant "least *evil*" so I think we are in agreement.

I think you are correct about the billing/Stripe setup. I will check the Stripe docs to confirm.

**Comment by pkarman** [comment] 2015-02-25 18:22
Some implementation notes, based on a reading of the Stripe docs.

* all new customers should have **trial_end** set to last_day_of_current_month:23:59:59 and **prorate** to false.
This can go into effect first, after testing is complete.

* all existing customers will need to be migrated to first-of-the-month billing cycle by updating their existing records with **trial_end** set to last_day_of_current_month:23:59:59 and **prorate** set to false.
We should try to time the migrations to start on a rolling basis, on the first day of the month. That way there is Least Surprise for the customer.

Example: a current customer with billing cycle date of March 5 should be moved on March 4. That gives them a trial of 26 days (5 .. 31) and means they won't be automatically billed in March, but will need to be manually charged for those 25 days.

Example: a new customer who signs up on March 5 would not be charged until April 1 and would need a manual prorated charge of 26 days issued to their card.

I'm not entirely sure about the existing customer scenario, so we should try it with a couple of friendly customers (even ourselves) to verify it works as expected.

**Comment by pkarman** [comment] 2015-02-27 05:32
I've pushed a monthly-billing branch to github with a lot of stripe-related changes, including a gem update. It passes all my rake tests, so I'm going to tag this ticket as ready to test and we can talk about timing.

**Comment by pkarman** [comment] 2015-02-27 19:06
after talking with @annewootton going to move this out of Dolly cycle so it can be tested independently.

**Comment by pkarman** [comment] 2015-02-27 19:43
note to @tarakieffer https://stripe.com/docs/testing#cards

**Comment by tarakieffer** [comment] 2015-03-04 03:22
Created new user upgraded and downgraded the plan.  After each change, the Stripe page indicating the new plan level and "Trialing until Mar 31"  This seems 
![screen shot 2015-03-03 at 8 50 39 pm](https://cloud.githubusercontent.com/assets/9256525/6477265/018b07b4-c1e7-11e4-85d1-ff6b2d69564a.png)

The account page in PUA also indicates the account is on trial.  @pkarman @annewootton Is this okay/expected?
![screen shot 2015-03-03 at 8 48 50 pm](https://cloud.githubusercontent.com/assets/9256525/6477284/617ee47e-c1e7-11e4-8dde-cc6dfacbbec8.png)


Upgrading an existing user, a pro-rated credit for old plan and pro-rated charge for the new plan is added to the next invoice.
![screen shot 2015-03-03 at 9 09 09 pm](https://cloud.githubusercontent.com/assets/9256525/6477458/b8faf948-c1e9-11e4-95ed-45f2928abe93.png)


So other then the messaging on the account page, this appears to be working as expected.

**Comment by pkarman** [comment] 2015-03-04 03:32
good catch @tarakieffer about the display on the account page. We should make that somehow conditional for a "real trial" vs this "pseudo trial".

Otherwise, yes, you're describing everything I would expect.

**Comment by pkarman** [comment] 2015-03-04 17:32
I have tried to disambiguate a real trial from this "interim" pseudo trial on the account page.

**Comment by tarakieffer** [comment] 2015-03-05 04:42
I am not seeing the trial language on the new user.

How does a real trial get set up?

**Comment by annewootton** [comment] 2015-03-05 17:30
"Real" trials, at least as I think you mean it, get set up manually by our
sales staff (i.e. me and Emily). Let me know if that doesn't answer your
question though!
ᐧ

**Comment by tarakieffer** [comment] 2015-03-05 18:06
That does answer my question, and now I have a new one. 

How important is it to be sure the countdown for the trial displays on the account page for the ones you manually set up?  If it is important, would you be kind enough to set one up in test so we/I can confirm it still does?  If it is not so important, I believe this ticket can be marked as ready-to-deploy.

**Comment by annewootton** [comment] 2015-03-05 19:03
Sure thing! Give me an email/account you're using in Stripe test?

**Comment by tarakieffer** [comment] 2015-03-05 19:33
tarakieffer612+popup9@gmail.com - Samuel - 1464   Thanks.

**Comment by annewootton** [comment] 2015-03-05 20:02
Thanks! You should now be trialing on the 1hr/mo Professional plan through
4/30/15.

See what you find on the account page...
ᐧ

**Comment by tarakieffer** [comment] 2015-03-05 20:28
Thanks, @annewootton.

For the new user, I see no mention of trialling on the account page.  
![screen shot 2015-03-05 at 2 25 45 pm](https://cloud.githubusercontent.com/assets/9256525/6513856/b380750a-c343-11e4-91de-a207ad8e843c.png)

For the user manually set up for trial, I see the trial countdown.
![screen shot 2015-03-05 at 2 24 42 pm](https://cloud.githubusercontent.com/assets/9256525/6513857/b384828a-c343-11e4-8d48-bd7d1797ac80.png)

**Comment by annewootton** [comment] 2015-03-05 20:33
Looks good to me.
ᐧ

**Closed** 2015-03-12 17:22 UTC
Labels: high, live-in-staging, ready-to-deploy
