### ISSUE TITLE
Not able to change plans 

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1085] opened 2015-04-28 14:36 UTC
In stage, I am attempting to change Ashley - tarakieffer612+popup6@gmail.com from the community plan to the 1 hour plan.  It looks like I am getting a 500 error which is preventing me from doing this.

**Comment by pkarman** [comment] 2015-04-28 15:04
this was due to an expired credit card. I have pushed a fix in 2c49921

**Comment by tarakieffer** [comment] 2015-05-04 19:36
I don't think the fix is as expected.  With Frederick who has an expiration date for the credit card of 4/2015, I am able to change plans.   

I had presumed an error message would display to the user.  Is this correct, @pkarman ?

**Comment by pkarman** [comment] 2015-05-04 19:47
Looking at the Stripe logs, I think this may be complicated by the fact that none of the stage data is first-day-of-the-month aligned like production is.

In any case, I would treat this as a regression test. What we want is for errors to be surfaced to the user rather than buried. In this case, there was no error because no charge was attempted (i.e. user was already on a paid plan and simply got pro-rated to the end of the month).

I.e. I think there was no error message because Stripe did not report an error. That seems like a different problem to me, and doesn't indicate a regression in this case, imo.

**Comment by tarakieffer** [comment] 2015-05-07 17:11
Makes sense.

**Closed** 2015-05-08 03:18 UTC
Labels: live-in-staging, ready-to-deploy, ready-to-test
