### ISSUE TITLE
Create messaging for users who upload silent files

### ISSUE THREAD

**Issue by Saltzshaker** [popuparchive/pop-up-archive#1290] opened 2015-10-26 17:37 UTC
If a user uploads a silent file, VB returns a "VB job empty" error. In this scenario, have notification alert on item page that says "This file has no content." 

Example: https://www.popuparchive.com/superadmin/tasks/448928
https://www.popuparchive.com/superadmin/items/45729

**Comment by Saltzshaker** [comment] 2015-11-18 19:14
@AndersEverett is writing an rspec test.

**Comment by Saltzshaker** [comment] 2015-11-23 18:07
Uploaded a silent file to staging. UI shows "Status: Cancelled." 
![screen shot 2015-11-23 at 10 04 45 am](https://cloud.githubusercontent.com/assets/8497203/11345132/fe1af0e0-91c9-11e5-9d03-c0e42183bc4a.png)
UI: https://stage.popuparchive.com/collections/2580/items/44593
Tasks: https://stage.popuparchive.com/superadmin/tasks?q%5Bowner_id_equals%5D=51258&q%5Bowner_type_equals%5D=AudioFile

**Comment by Saltzshaker** [comment] 2015-11-23 19:06
@AndersEverett will cherrypick this commit to master so that we can test uploading without having weird VB-in-staging issues (to be addressed in https://github.com/popuparchive/pop-up-archive/issues/1313)

**Comment by Saltzshaker** [comment] 2015-11-23 23:00
@AndersEverett Several VB tasks have been created and cancelled, so it gets stuck in working. UI still says "Transcribing"
![screen shot 2015-11-23 at 2 59 34 pm](https://cloud.githubusercontent.com/assets/8497203/11352726/f0768da4-91f2-11e5-9f2e-73213398ff0b.png)
  https://www.popuparchive.com/superadmin/items/46563

**Comment by AndersEverett** [comment] 2015-11-23 23:05
@Saltzshaker  These all have "Voicebase job failed" error message. Ticket was in response to "Voicebase job empty" error message. Do we want to add UI messaging for "Voicebase job failed" message too?

**Comment by Saltzshaker** [comment] 2015-11-23 23:08
Hm, that's weird that the response would be different. 

As for adding UI messaging for "Voicebase job failed," I guess it depends on what other possible causes there are for "Voicebase job failed." We might want to make it a more generic message linking to an FAQ page with possible causes that includes "silent file." @baileyspace, do you know other reasons why a file would have a failed VB task? Are the files ever salvageable?

**Comment by annewootton** [comment] 2015-11-23 23:25
If they're truly silent files, how would they be salvaged?

**Comment by Saltzshaker** [comment] 2015-11-23 23:45
I meant if it returned "VB job failed" for reasons other than silent files.

**Comment by annewootton** [comment] 2015-11-24 00:12
Ah, it wasn't immediately clear to me that the response "job failed" could be caused by something other than silence. If that's the case, we should try to fix that, and move forward with testing the "job empty" response + messaging here.

**Comment by Saltzshaker** [comment] 2015-11-24 01:06
Can't replicate. Moving to general to do.

**Comment by annewootton** [comment] 2015-11-30 19:46
Clarifying for future: if we don't get a callback from Voicebase and generate our own "VB job failed" error message, we keep retrying the job for 24 hours. Therefore, any UI status we want to provide should be (is?) based not on that "VB job failed" error but rather on the actual task status, i.e. a failed task should get UI status that transcription failed, but if the task is still "working" or "canceled" it should still have the UI status of "Transcribing."

**Comment by annewootton** [comment] 2015-11-30 23:07
Closing this in favor of #1315

**Closed** 2015-11-30 23:07 UTC
Labels: live-in-staging, low
