### ISSUE TITLE
Basic Transcripts are not completing

### ISSUE THREAD

**Issue by tarakieffer** [popuparchive/pop-up-archive#1122] opened 2015-05-30 23:01 UTC
Uploaded file:
https://stage.popuparchive.com/superadmin/audio_files/29755

Added by link:
https://stage.popuparchive.com/superadmin/audio_files/29756

Both were added to a collection that was created on Friday.  https://stage.popuparchive.com/superadmin/collections/3752

**Comment by pkarman** [comment] 2015-05-31 03:52
the problem is that fixer doesn't seem to let me create a sequence of tasks the way it used to. I have opened this ticket to track the issue upstream: https://github.com/PRX/fixer.prx.org/issues/33

**Comment by pkarman** [comment] 2015-06-01 15:09
PR created and approved: https://github.com/PRX/fixer.prx.org/pull/34

**Comment by kookster** [comment] 2015-06-01 17:29
and now merged.

**Comment by pkarman** [comment] 2015-06-01 19:03
confirmed that PRX/fixer.prx.org#34 fixed this particular problem.

there are still some issues, tracking upstream in https://github.com/PRX/fixer_client/issues/2 and https://github.com/PRX/audio_monster/issues/8

**Comment by pkarman** [comment] 2015-06-02 19:52
upstream issues seem resolved, and I was able to recover one of the troubled files:
https://stage.popuparchive.com/superadmin/audio_files/29755

I would suggest testing this again from the top with a new item.

**Comment by tarakieffer** [comment] 2015-06-10 16:27
I tried this again this morning.  I did have four files complete, but I never received an email notification.

https://stage.popuparchive.com/superadmin/audio_files/29773
https://stage.popuparchive.com/superadmin/audio_files/29774
https://stage.popuparchive.com/superadmin/audio_files/29775
https://stage.popuparchive.com/superadmin/audio_files/29776

I did get impatient after 30 mins or so on a couple of them and clicked 'Recover.'

**Comment by tarakieffer** [comment] 2015-06-10 16:51
My mistake. These were all preview transcripts and therefore should not get the email notification.  So these all work as expected.

**Closed** 2015-07-07 03:25 UTC
Labels: bug, live-in-staging, ready-to-deploy, ready-to-test
